syntax = "proto3";

package core.corepb.v1;

import "core.proto";
import "google/protobuf/any.proto";

message QBFTMsg {
  int64                   type                  = 1;
  core.corepb.v1.Duty     duty                  = 2;
  int64                   peer_idx              = 3;
  int64                   round                 = 4;
  reserved                                        5;
  int64                   prepared_round        = 6;
  reserved                                        7;
  bytes                   signature             = 8;
  reserved                                        9;
  reserved                                        10;
  bytes                   value_hash            = 11;
  bytes                   prepared_value_hash   = 12;
}

message QBFTConsensusMsg {
  QBFTMsg                       msg            = 1; 
  repeated QBFTMsg              justification  = 2;
  repeated google.protobuf.Any  values         = 3; 
}
